sonar.projectKey=django-blog1
sonar.projectName=Django Blog1
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10
sonar.exclusions=**/migrations/**, **/__pycache__/**, **/tests/**, **/venv**
sonar.token=squ_525f04c5e2aa3339a02476dbbe9016d40c9c768b
